language: "node_js"
node_js:
  - "0.10"
before_install:
 - "npm install -g grunt-cli"
 - "npm install istanbul -g"
 - "npm install coveralls -g"
install: npm install
before_script: grunt
script: "npm run-script ci"
after_success:
  - "npm run-script ci"
  - "grunt coveralls"
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage